name 'workstation'
maintainer 'zamott'
maintainer_email 'tomaz.r.martins@gmail.com'
license 'All Rights Reserved'
description 'Installs/Configures workstation'
long_description 'Installs/Configures workstation'
version '0.1.0'
chef_version '>= 13.0'
